version: 2
jobs:
  build:
    docker:
      - image: node:8
    steps:
      - checkout
      - run: yarn install
      - run: yarn run gulp package
      - store_artifacts:
        path: ./extension.zip
